<option value = ""></option>
<option value = "143b cells">143b cells</option>
<option value = "143b osteosarcoma cells">143b osteosarcoma cells</option>
<option value = "23s_fragment_depletion">23s_fragment_depletion</option>
<option value = "23s_fragment_enrichment">23s_fragment_enrichment</option>
<option value = "23s_rrna_enrichment">23s_rrna_enrichment</option>
<option value = "293t hek cell line">293t hek cell line</option>
<option value = "3t3-l1 cells">3t3-l1 cells</option>
<option value = "5637 cells">5637 cells</option>
<option value = "a2780 human ovarian cancer cells">a2780 human ovarian cancer cells</option>
<option value = "a375 melanoma cells">a375 melanoma cells</option>
<option value = "a375m cells">a375m cells</option>
<option value = "a549 cell">a549 cell</option>
<option value = "a549 cell culture media">a549 cell culture media</option>
<option value = "a549 cells">a549 cells</option>
<option value = "a549 human lung cancer cell">a549 human lung cancer cell</option>
<option value = "a549 human lung epithelial cells">a549 human lung epithelial cells</option>
<option value = "abdomen">abdomen</option>
<option value = "acorns">acorns</option>
<option value = "acute myeloid leukemia (aml) cell">acute myeloid leukemia (aml) cell</option>
<option value = "adherent cell lines">adherent cell lines</option>
<option value = "adherent cultured mammalian cells">adherent cultured mammalian cells</option>
<option value = "adipocyte media">adipocyte media</option>
<option value = "adipocytes">adipocytes</option>
<option value = "adipose">adipose</option>
<option value = "adipose pannus">adipose pannus</option>
<option value = "adipose tissue">adipose tissue</option>
<option value = "adrenal gland">adrenal gland</option>
<option value = "algae">algae</option>
<option value = "algae oil">algae oil</option>
<option value = "aml cells">aml cells</option>
<option value = "amniotic fluid">amniotic fluid</option>
<option value = "amygadala">amygadala</option>
<option value = "anther">anther</option>
<option value = "aortic valve tissue">aortic valve tissue</option>
<option value = "apoplastic washing fluid">apoplastic washing fluid</option>
<option value = "aqueous humor">aqueous humor</option>
<option value = "arteries">arteries</option>
<option value = "artery plasma">artery plasma</option>
<option value = "artificial sea water">artificial sea water</option>
<option value = "astrocytes">astrocytes</option>
<option value = "atc1 pancreatic non-malignant immortalized cells">atc1 pancreatic non-malignant immortalized cells</option>
<option value = "b-cells">b-cells</option>
<option value = "bacteria">bacteria</option>
<option value = "bacterial cells">bacterial cells</option>
<option value = "bacterial culture supernatant">bacterial culture supernatant</option>
<option value = "bacterial media">bacterial media</option>
<option value = "bacterial origin">bacterial origin</option>
<option value = "bacterial supernatant">bacterial supernatant</option>
<option value = "bacteroides fragilis cells">bacteroides fragilis cells</option>
<option value = "bacteroides thetaiotaomicron cells">bacteroides thetaiotaomicron cells</option>
<option value = "balf">balf</option>
<option value = "bee head">bee head</option>
<option value = "beef feed">beef feed</option>
<option value = "biofilm">biofilm</option>
<option value = "biopsy">biopsy</option>
<option value = "bladder">bladder</option>
<option value = "blastocysts">blastocysts</option>
<option value = "blood">blood</option>
<option value = "blubber">blubber</option>
<option value = "bon1 pancreatic cancer cells">bon1 pancreatic cancer cells</option>
<option value = "bone">bone</option>
<option value = "bone marrow">bone marrow</option>
<option value = "bone marrow derived macrophages">bone marrow derived macrophages</option>
<option value = "bone marrow primary cell">bone marrow primary cell</option>
<option value = "bone marrow secondary cell">bone marrow secondary cell</option>
<option value = "bone sarcoma cells">bone sarcoma cells</option>
<option value = "bovine aortic endothelial cells">bovine aortic endothelial cells</option>
<option value = "bovine meat">bovine meat</option>
<option value = "bovine_meat">bovine_meat</option>
<option value = "brain">brain</option>
<option value = "brain-cortex">brain-cortex</option>
<option value = "brain - cerebral hemisphere">brain - cerebral hemisphere</option>
<option value = "brain cancer cells">brain cancer cells</option>
<option value = "brain cortex">brain cortex</option>
<option value = "brain organoids">brain organoids</option>
<option value = "brain tissue">brain tissue</option>
<option value = "brainstem">brainstem</option>
<option value = "brassica oleracea l. var. capitata f. capitata cv. "dottenfelder dauer"">brassica oleracea l. var. capitata f. capitata cv. "dottenfelder dauer"</option>
<option value = "brassica oleracea l. var. capitata f. rubra "integro"">brassica oleracea l. var. capitata f. rubra "integro"</option>
<option value = "brassica oleracea l. var. capitata f. rubra cv. "davaro"">brassica oleracea l. var. capitata f. rubra cv. "davaro"</option>
<option value = "brassica oleracea l. var. italica cv. "calinaro"">brassica oleracea l. var. italica cv. "calinaro"</option>
<option value = "brassica plant tissues">brassica plant tissues</option>
<option value = "breast">breast</option>
<option value = "breast cancer cell line">breast cancer cell line</option>
<option value = "breast cancer cells">breast cancer cells</option>
<option value = "breast milk">breast milk</option>
<option value = "breast tissue">breast tissue</option>
<option value = "breath">breath</option>
<option value = "brine shrimp">brine shrimp</option>
<option value = "bronchoalveolar lavage">bronchoalveolar lavage</option>
<option value = "brown adipose">brown adipose</option>
<option value = "brown adipose tissue">brown adipose tissue</option>
<option value = "brown fat tissue">brown fat tissue</option>
<option value = "bt-474">bt-474</option>
<option value = "bt-474 breast cancer cells">bt-474 breast cancer cells</option>
<option value = "bt-474 xenograft in an nsg mouse">bt-474 xenograft in an nsg mouse</option>
<option value = "buccal">buccal</option>
<option value = "bulk soil">bulk soil</option>
<option value = "c2c12 myoblast cells">c2c12 myoblast cells</option>
<option value = "c57/bl6 mouse liver tissue">c57/bl6 mouse liver tissue</option>
<option value = "cal120 breast cancer cells">cal120 breast cancer cells</option>
<option value = "candida auris dispersed cells">candida auris dispersed cells</option>
<option value = "candida auris planktonic cells">candida auris planktonic cells</option>
<option value = "canine cancer cells">canine cancer cells</option>
<option value = "capsicum chinense">capsicum chinense</option>
<option value = "cardiac blood">cardiac blood</option>
<option value = "cardiac mitochondria">cardiac mitochondria</option>
<option value = "cardiac tissue">cardiac tissue</option>
<option value = "cardiomyocyte cells">cardiomyocyte cells</option>
<option value = "carotid artery tissue">carotid artery tissue</option>
<option value = "cd8 t cell">cd8 t cell</option>
<option value = "cecal content">cecal content</option>
<option value = "cecal contents">cecal contents</option>
<option value = "cecum">cecum</option>
<option value = "cecum tissue">cecum tissue</option>
<option value = "cell culture media">cell culture media</option>
<option value = "cell culture supernatant">cell culture supernatant</option>
<option value = "cell lysate">cell lysate</option>
<option value = "cell pellet (extracted from rpf)">cell pellet (extracted from rpf)</option>
<option value = "cells">cells</option>
<option value = "centella callus">centella callus</option>
<option value = "cerebral cortex">cerebral cortex</option>
<option value = "cerebrospinal fluid">cerebrospinal fluid</option>
<option value = "ch12 b lymphoma cells">ch12 b lymphoma cells</option>
<option value = "chicken meat">chicken meat</option>
<option value = "cho cells">cho cells</option>
<option value = "choroid plexus">choroid plexus</option>
<option value = "chow diet">chow diet</option>
<option value = "cns">cns</option>
<option value = "colerectal cancer cells">colerectal cancer cells</option>
<option value = "colon">colon</option>
<option value = "colon tumor tissue">colon tumor tissue</option>
<option value = "colorectal adenocarcinoma tumor">colorectal adenocarcinoma tumor</option>
<option value = "colorectal tissue">colorectal tissue</option>
<option value = "colorectum tissue">colorectum tissue</option>
<option value = "combination_1h">combination_1h</option>
<option value = "combination_3h">combination_3h</option>
<option value = "combination_6h">combination_6h</option>
<option value = "conditioned media">conditioned media</option>
<option value = "conditioned treatment media">conditioned treatment media</option>
<option value = "control_1h">control_1h</option>
<option value = "control_3h">control_3h</option>
<option value = "control_6h">control_6h</option>
<option value = "coq9 0.001âµm standard">coq9 0.001âµm standard</option>
<option value = "coq9 0.01âµm standard">coq9 0.01âµm standard</option>
<option value = "coq9 0.1âµm standard">coq9 0.1âµm standard</option>
<option value = "coq9 0.25âµm standard">coq9 0.25âµm standard</option>
<option value = "coq9 0.5âµm standard">coq9 0.5âµm standard</option>
<option value = "coq9 10âµm standard">coq9 10âµm standard</option>
<option value = "coq9 1âµm standard">coq9 1âµm standard</option>
<option value = "coq9 5âµm standard">coq9 5âµm standard</option>
<option value = "coral nubbins">coral nubbins</option>
<option value = "cord blood">cord blood</option>
<option value = "cord blood (serum)">cord blood (serum)</option>
<option value = "corpus luteum">corpus luteum</option>
<option value = "cortex">cortex</option>
<option value = "csf">csf</option>
<option value = "ct26 murine colon cancer cells">ct26 murine colon cancer cells</option>
<option value = "culture media">culture media</option>
<option value = "cultured cell line">cultured cell line</option>
<option value = "cultured cells">cultured cells</option>
<option value = "cultured colerectal cancer cells">cultured colerectal cancer cells</option>
<option value = "cultured diatom cells">cultured diatom cells</option>
<option value = "cultured fibroblasts">cultured fibroblasts</option>
<option value = "cultured human myotubes with toxoplasma gondii">cultured human myotubes with toxoplasma gondii</option>
<option value = "cultured kidney cells">cultured kidney cells</option>
<option value = "cultured plankton cells">cultured plankton cells</option>
<option value = "cultured plasmodium falciparum">cultured plasmodium falciparum</option>
<option value = "cultured plasmodium falciparum ii3">cultured plasmodium falciparum ii3</option>
<option value = "cultured primary cells">cultured primary cells</option>
<option value = "cultured prochlorococcus cells and vesicles">cultured prochlorococcus cells and vesicles</option>
<option value = "cultured_astrocytes">cultured_astrocytes</option>
<option value = "cyst fluid">cyst fluid</option>
<option value = "date palm fruit">date palm fruit</option>
<option value = "decoction">decoction</option>
<option value = "dendritic cells">dendritic cells</option>
<option value = "diatom cells/particulate matter from sea ice cores">diatom cells/particulate matter from sea ice cores</option>
<option value = "diet">diet</option>
<option value = "digestive fluid">digestive fluid</option>
<option value = "dissected organizer from xenopus laevis">dissected organizer from xenopus laevis</option>
<option value = "dorsal root ganglia">dorsal root ganglia</option>
<option value = "drg">drg</option>
<option value = "dried long pepper">dried long pepper</option>
<option value = "dry blood spot">dry blood spot</option>
<option value = "dsi">dsi</option>
<option value = "dunnart oat cultivar">dunnart oat cultivar</option>
<option value = "duodenum">duodenum</option>
<option value = "e coli cells">e coli cells</option>
<option value = "e. coli">e. coli</option>
<option value = "e. coli cultured in terrific broth (tb) medium">e. coli cultured in terrific broth (tb) medium</option>
<option value = "edta plasma">edta plasma</option>
<option value = "eggs">eggs</option>
<option value = "elim control">elim control</option>
<option value = "elim dcaa">elim dcaa</option>
<option value = "embryo">embryo</option>
<option value = "embryonic cells">embryonic cells</option>
<option value = "embryonic csf">embryonic csf</option>
<option value = "embryonic fibroblasts (pfa1)">embryonic fibroblasts (pfa1)</option>
<option value = "embryonic serum">embryonic serum</option>
<option value = "embyronic liver">embyronic liver</option>
<option value = "endothelial cells">endothelial cells</option>
<option value = "enzyme assay">enzyme assay</option>
<option value = "epidermis">epidermis</option>
<option value = "epididymal adipose tissue">epididymal adipose tissue</option>
<option value = "epithelial cells">epithelial cells</option>
<option value = "eplasmaididymal fat">eplasmaididymal fat</option>
<option value = "erythrocytes">erythrocytes</option>
<option value = "esophagus">esophagus</option>
<option value = "exhaled breath condensate">exhaled breath condensate</option>
<option value = "extracellular fluid">extracellular fluid</option>
<option value = "eye">eye</option>
<option value = "eye lens tissue">eye lens tissue</option>
<option value = "eye tissue">eye tissue</option>
<option value = "face">face</option>
<option value = "fbs-based standard">fbs-based standard</option>
<option value = "feces">feces</option>
<option value = "femoral muscle">femoral muscle</option>
<option value = "fetus blood">fetus blood</option>
<option value = "fibroblasts">fibroblasts</option>
<option value = "fibrous root">fibrous root</option>
<option value = "fish larvae">fish larvae</option>
<option value = "flushing">flushing</option>
<option value = "fly">fly</option>
<option value = "fly body">fly body</option>
<option value = "fly head">fly head</option>
<option value = "fly heads">fly heads</option>
<option value = "follicular fluid">follicular fluid</option>
<option value = "food">food</option>
<option value = "foreskin">foreskin</option>
<option value = "fruit">fruit</option>
<option value = "fruit juice">fruit juice</option>
<option value = "fruit_flour">fruit_flour</option>
<option value = "fungal cells">fungal cells</option>
<option value = "fungal mycelium">fungal mycelium</option>
<option value = "fungal/bacterial volatiles">fungal/bacterial volatiles</option>
<option value = "fungi">fungi</option>
<option value = "galea">galea</option>
<option value = "gallbladder">gallbladder</option>
<option value = "gastrocnemius">gastrocnemius</option>
<option value = "gill">gill</option>
<option value = "glioblastoma cells">glioblastoma cells</option>
<option value = "glioma cells">glioma cells</option>
<option value = "gut">gut</option>
<option value = "h1299 lung cancer cell line">h1299 lung cancer cell line</option>
<option value = "h441 cell culture media">h441 cell culture media</option>
<option value = "h441 human lung cancer cell">h441 human lung cancer cell</option>
<option value = "hcc1806 breast cancer cells">hcc1806 breast cancer cells</option>
<option value = "hct116 colon cancer cells">hct116 colon cancer cells</option>
<option value = "head">head</option>
<option value = "head and neck cancer cell line">head and neck cancer cell line</option>
<option value = "head tissue">head tissue</option>
<option value = "heart">heart</option>
<option value = "heart tissue">heart tissue</option>
<option value = "hek cells">hek cells</option>
<option value = "hek293">hek293</option>
<option value = "hek293_hadv5">hek293_hadv5</option>
<option value = "hek293t cultured cells">hek293t cultured cells</option>
<option value = "hek293t embryonic kidney cells">hek293t embryonic kidney cells</option>
<option value = "hela">hela</option>
<option value = "hela cells">hela cells</option>
<option value = "hemolymph">hemolymph</option>
<option value = "hep g2 cells">hep g2 cells</option>
<option value = "hepa 1 cells">hepa 1 cells</option>
<option value = "hepatopancreas tissue">hepatopancreas tissue</option>
<option value = "hindbrain">hindbrain</option>
<option value = "hippocampus">hippocampus</option>
<option value = "honey bee egg">honey bee egg</option>
<option value = "hs578t breast cancer cells">hs578t breast cancer cells</option>
<option value = "ht1080 human epithelial cancer cells">ht1080 human epithelial cancer cells</option>
<option value = "huh-7 cells">huh-7 cells</option>
<option value = "huh7 cells">huh7 cells</option>
<option value = "huh7 media">huh7 media</option>
<option value = "human bmsc">human bmsc</option>
<option value = "human breast cancer cells">human breast cancer cells</option>
<option value = "human breast epithelial and adipose tissue">human breast epithelial and adipose tissue</option>
<option value = "human breast milk">human breast milk</option>
<option value = "human embryonic kidney (hek) 293t cells">human embryonic kidney (hek) 293t cells</option>
<option value = "human feces">human feces</option>
<option value = "human glioblastoma u251 cell line">human glioblastoma u251 cell line</option>
<option value = "human liver cancer cells">human liver cancer cells</option>
<option value = "human lung epithelial cells a549-ace2">human lung epithelial cells a549-ace2</option>
<option value = "human monocyte-derived macrophages (hmdm)">human monocyte-derived macrophages (hmdm)</option>
<option value = "human osteosarcoma u2-os cells">human osteosarcoma u2-os cells</option>
<option value = "human renal 769p cells">human renal 769p cells</option>
<option value = "human renal caki1 cells">human renal caki1 cells</option>
<option value = "human seminal fluid">human seminal fluid</option>
<option value = "human serum">human serum</option>
<option value = "human serum from commercial source">human serum from commercial source</option>
<option value = "human subcutaneous adipocytes">human subcutaneous adipocytes</option>
<option value = "hypothalamus">hypothalamus</option>
<option value = "icc13-7">icc13-7</option>
<option value = "icc13-7 xenograft">icc13-7 xenograft</option>
<option value = "ileum">ileum</option>
<option value = "in vitro transcription">in vitro transcription</option>
<option value = "induced neural stem cell">induced neural stem cell</option>
<option value = "inguinal white adipose tissue">inguinal white adipose tissue</option>
<option value = "insect brain">insect brain</option>
<option value = "insect tissue">insect tissue</option>
<option value = "internal standard dry">internal standard dry</option>
<option value = "internal standard extracted from water">internal standard extracted from water</option>
<option value = "interstitial fluid">interstitial fluid</option>
<option value = "intestinal content">intestinal content</option>
<option value = "intestinal contents (small intestine)">intestinal contents (small intestine)</option>
<option value = "intestinal epithelial cells">intestinal epithelial cells</option>
<option value = "intestinal lumen contents">intestinal lumen contents</option>
<option value = "intestine">intestine</option>
<option value = "ipsc">ipsc</option>
<option value = "ipsc cells">ipsc cells</option>
<option value = "isolated bone">isolated bone</option>
<option value = "j774a.1_murine_macrophages">j774a.1_murine_macrophages</option>
<option value = "jejunum">jejunum</option>
<option value = "jurkat cells, clone e6-1">jurkat cells, clone e6-1</option>
<option value = "k562 cells">k562 cells</option>
<option value = "keratinocytes">keratinocytes</option>
<option value = "kidney">kidney</option>
<option value = "kidney cortex">kidney cortex</option>
<option value = "kidney epithelial cells">kidney epithelial cells</option>
<option value = "kidney outer medulla">kidney outer medulla</option>
<option value = "kidney; serum">kidney; serum</option>
<option value = "larvae">larvae</option>
<option value = "larval fish heads/brain">larval fish heads/brain</option>
<option value = "latex">latex</option>
<option value = "leaf">leaf</option>
<option value = "leaves">leaves</option>
<option value = "leu10-teixobactin_1h">leu10-teixobactin_1h</option>
<option value = "leu10-teixobactin_3h">leu10-teixobactin_3h</option>
<option value = "leu10-teixobactin_6h">leu10-teixobactin_6h</option>
<option value = "leukemia cell line k-562">leukemia cell line k-562</option>
<option value = "leukemia cells">leukemia cells</option>
<option value = "liver">liver</option>
<option value = "liver cancer cell line">liver cancer cell line</option>
<option value = "liver tissue">liver tissue</option>
<option value = "liver tumor">liver tumor</option>
<option value = "lncap cells">lncap cells</option>
<option value = "lung">lung</option>
<option value = "lung airways">lung airways</option>
<option value = "lung embryonic fibroblasts">lung embryonic fibroblasts</option>
<option value = "lung organoids">lung organoids</option>
<option value = "lung tumors">lung tumors</option>
<option value = "lymph fluid">lymph fluid</option>
<option value = "lymph node">lymph node</option>
<option value = "lymphoma cells">lymphoma cells</option>
<option value = "m. mycoides">m. mycoides</option>
<option value = "macrophages">macrophages</option>
<option value = "maize kernel">maize kernel</option>
<option value = "maize starchy endosperm">maize starchy endosperm</option>
<option value = "marine particulate organic matter">marine particulate organic matter</option>
<option value = "maternal liver">maternal liver</option>
<option value = "maternal serum">maternal serum</option>
<option value = "mature seeds">mature seeds</option>
<option value = "mc38 murine colorectal tumor">mc38 murine colorectal tumor</option>
<option value = "mc38 murine whole tumor">mc38 murine whole tumor</option>
<option value = "mcf7 breast cancer cells">mcf7 breast cancer cells</option>
<option value = "mda-mb-231 breast cancer cell">mda-mb-231 breast cancer cell</option>
<option value = "mda-mb-231 breast cancer cells">mda-mb-231 breast cancer cells</option>
<option value = "mda-mb-468 breast cancer cells">mda-mb-468 breast cancer cells</option>
<option value = "mdh assay">mdh assay</option>
<option value = "mdixon(media)">mdixon(media)</option>
<option value = "media">media</option>
<option value = "melanoma cells">melanoma cells</option>
<option value = "merozoites isolated from rbc">merozoites isolated from rbc</option>
<option value = "mesenchymal stromal cells">mesenchymal stromal cells</option>
<option value = "mesenteric lymph">mesenteric lymph</option>
<option value = "microbial biofilm">microbial biofilm</option>
<option value = "microglia">microglia</option>
<option value = "milk">milk</option>
<option value = "minimal cell jcvi-syn3b">minimal cell jcvi-syn3b</option>
<option value = "mitochondria">mitochondria</option>
<option value = "mitochondria ip lipidomics">mitochondria ip lipidomics</option>
<option value = "monocytes">monocytes</option>
<option value = "mononuclear cells">mononuclear cells</option>
<option value = "mouse back of eye">mouse back of eye</option>
<option value = "mouse back of eye (choroid/rpe)">mouse back of eye (choroid/rpe)</option>
<option value = "mouse cecum">mouse cecum</option>
<option value = "mouse feces">mouse feces</option>
<option value = "mouse liver">mouse liver</option>
<option value = "mouse lungs">mouse lungs</option>
<option value = "mouse paw skin">mouse paw skin</option>
<option value = "mouse pdac cell line">mouse pdac cell line</option>
<option value = "mouse plasma">mouse plasma</option>
<option value = "mouse retina">mouse retina</option>
<option value = "mouse serum">mouse serum</option>
<option value = "mouse small intestine">mouse small intestine</option>
<option value = "mouse tissues and interstitial fluids">mouse tissues and interstitial fluids</option>
<option value = "msi">msi</option>
<option value = "multiple tissues">multiple tissues</option>
<option value = "murine bone marrow derived macrophages">murine bone marrow derived macrophages</option>
<option value = "murine brain">murine brain</option>
<option value = "murine breast cancer cells">murine breast cancer cells</option>
<option value = "murine heart">murine heart</option>
<option value = "murine liver">murine liver</option>
<option value = "murine macrophage cells">murine macrophage cells</option>
<option value = "murine peritoneal macrophage cells">murine peritoneal macrophage cells</option>
<option value = "murine peritoneal macrophages">murine peritoneal macrophages</option>
<option value = "murine plasma">murine plasma</option>
<option value = "murine plasma - pharmacokinetics experiment">murine plasma - pharmacokinetics experiment</option>
<option value = "murine plasma spiked with fasnall">murine plasma spiked with fasnall</option>
<option value = "muscle">muscle</option>
<option value = "muscle (gastrocnemius)">muscle (gastrocnemius)</option>
<option value = "muscle (quadriceps)">muscle (quadriceps)</option>
<option value = "muscle cell">muscle cell</option>
<option value = "muscle satellite cell">muscle satellite cell</option>
<option value = "mycelia in media">mycelia in media</option>
<option value = "nasal polyp tissue">nasal polyp tissue</option>
<option value = "neuro2a cells">neuro2a cells</option>
<option value = "neurons">neurons</option>
<option value = "neutrophils">neutrophils</option>
<option value = "nih3t3">nih3t3</option>
<option value = "nist standard reference material (srm 1950)">nist standard reference material (srm 1950)</option>
<option value = "non-small cell lung cancer cells">non-small cell lung cancer cells</option>
<option value = "notochord">notochord</option>
<option value = "nucleus accumbens">nucleus accumbens</option>
<option value = "old leaf">old leaf</option>
<option value = "optic chiasm">optic chiasm</option>
<option value = "optic nerve">optic nerve</option>
<option value = "organoid">organoid</option>
<option value = "osteoclast">osteoclast</option>
<option value = "outer medulla kidney">outer medulla kidney</option>
<option value = "ovarian cancer cells">ovarian cancer cells</option>
<option value = "ovaries">ovaries</option>
<option value = "ovary">ovary</option>
<option value = "panc-1">panc-1</option>
<option value = "pancreas">pancreas</option>
<option value = "pancreas tissue">pancreas tissue</option>
<option value = "pancreatic cancer cell allografts">pancreatic cancer cell allografts</option>
<option value = "pancreatic cancer cells">pancreatic cancer cells</option>
<option value = "pancreatic islets">pancreatic islets</option>
<option value = "parasite">parasite</option>
<option value = "paw skin">paw skin</option>
<option value = "pdx gbm - mouse brain tumor section">pdx gbm - mouse brain tumor section</option>
<option value = "perfusate">perfusate</option>
<option value = "peripheral blood mono-nuclear cells">peripheral blood mono-nuclear cells</option>
<option value = "peritoneal">peritoneal</option>
<option value = "peritoneal fluid">peritoneal fluid</option>
<option value = "peritoneal fluid lavage">peritoneal fluid lavage</option>
<option value = "peritoneal macrophages">peritoneal macrophages</option>
<option value = "pf infected rbcs">pf infected rbcs</option>
<option value = "pf3d7_infected_rbc">pf3d7_infected_rbc</option>
<option value = "photosynthetic organism">photosynthetic organism</option>
<option value = "phytoplankton">phytoplankton</option>
<option value = "pinus koraiensis leaf">pinus koraiensis leaf</option>
<option value = "pinus koraiensis leaf leachate">pinus koraiensis leaf leachate</option>
<option value = "placenta">placenta</option>
<option value = "plankton cells">plankton cells</option>
<option value = "plant">plant</option>
<option value = "plant leaves and roots">plant leaves and roots</option>
<option value = "plant root">plant root</option>
<option value = "plant root tissue">plant root tissue</option>
<option value = "plant roots">plant roots</option>
<option value = "plant seed">plant seed</option>
<option value = "plaque samples">plaque samples</option>
<option value = "plasma">plasma</option>
<option value = "plasma pool">plasma pool</option>
<option value = "plasma_edta">plasma_edta</option>
<option value = "plasmodium cells">plasmodium cells</option>
<option value = "platelets">platelets</option>
<option value = "polymyxin b_1h">polymyxin b_1h</option>
<option value = "polymyxin b_3h">polymyxin b_3h</option>
<option value = "polymyxin b_6h">polymyxin b_6h</option>
<option value = "pool embryonic csf">pool embryonic csf</option>
<option value = "pool embryonic serum">pool embryonic serum</option>
<option value = "pool maternal serum">pool maternal serum</option>
<option value = "pooled sample">pooled sample</option>
<option value = "primary mouse astrocytes">primary mouse astrocytes</option>
<option value = "prostate">prostate</option>
<option value = "prostate cancer cells">prostate cancer cells</option>
<option value = "proximal tubular cells">proximal tubular cells</option>
<option value = "psi">psi</option>
<option value = "qgp1 pancreatic cancer cells">qgp1 pancreatic cancer cells</option>
<option value = "queen bee head">queen bee head</option>
<option value = "rat vena cava powder">rat vena cava powder</option>
<option value = "rectum">rectum</option>
<option value = "red blood cells">red blood cells</option>
<option value = "reference_standards">reference_standards</option>
<option value = "renal cancer cells">renal cancer cells</option>
<option value = "renal tissue">renal tissue</option>
<option value = "retina">retina</option>
<option value = "retinal ganglion cells">retinal ganglion cells</option>
<option value = "rhizome">rhizome</option>
<option value = "rhizosphere">rhizosphere</option>
<option value = "rhizosphere soil">rhizosphere soil</option>
<option value = "rice grain">rice grain</option>
<option value = "rice leaves">rice leaves</option>
<option value = "right atrial tissue">right atrial tissue</option>
<option value = "root">root</option>
<option value = "rpe (retinal pigment epithelium)">rpe (retinal pigment epithelium)</option>
<option value = "rrna_depletion">rrna_depletion</option>
<option value = "saccharomyces cerevisiae">saccharomyces cerevisiae</option>
<option value = "saliva">saliva</option>
<option value = "sample type:acsf">sample type:acsf</option>
<option value = "sample type:dialysate">sample type:dialysate</option>
<option value = "sarcoma">sarcoma</option>
<option value = "scalp">scalp</option>
<option value = "sciatic nerve">sciatic nerve</option>
<option value = "seawater">seawater</option>
<option value = "seaweed">seaweed</option>
<option value = "seed">seed</option>
<option value = "seedlings">seedlings</option>
<option value = "seeds">seeds</option>
<option value = "seminal plasma">seminal plasma</option>
<option value = "serum">serum</option>
<option value = "sewage sludge">sewage sludge</option>
<option value = "shrimp organs">shrimp organs</option>
<option value = "si">si</option>
<option value = "skeletal muscle">skeletal muscle</option>
<option value = "skeletal myotubes">skeletal myotubes</option>
<option value = "skeleton">skeleton</option>
<option value = "skin">skin</option>
<option value = "skin biopsy">skin biopsy</option>
<option value = "small intestinal fecal contents">small intestinal fecal contents</option>
<option value = "small intestine">small intestine</option>
<option value = "snu-668 erastin-resistant cells">snu-668 erastin-resistant cells</option>
<option value = "soil">soil</option>
<option value = "spermatozoa">spermatozoa</option>
<option value = "spinal">spinal</option>
<option value = "spinal cord">spinal cord</option>
<option value = "spleen">spleen</option>
<option value = "spleen t-cells">spleen t-cells</option>
<option value = "splenocytes">splenocytes</option>
<option value = "sputum">sputum</option>
<option value = "stage 43 tadpoles">stage 43 tadpoles</option>
<option value = "standard">standard</option>
<option value = "standards (std)">standards (std)</option>
<option value = "staphylococcus aureus">staphylococcus aureus</option>
<option value = "staphylococcus epidermidis intracellular">staphylococcus epidermidis intracellular</option>
<option value = "std">std</option>
<option value = "stem cells">stem cells</option>
<option value = "stem cells culture media">stem cells culture media</option>
<option value = "stomach">stomach</option>
<option value = "stool">stool</option>
<option value = "sub ventricular zone tissue">sub ventricular zone tissue</option>
<option value = "subcutaneous fat">subcutaneous fat</option>
<option value = "subcutaneous tumor tissues of pancreatic cancer">subcutaneous tumor tissues of pancreatic cancer</option>
<option value = "subcutanous white adipose tissue">subcutanous white adipose tissue</option>
<option value = "succinate and fumarate reagent mixture">succinate and fumarate reagent mixture</option>
<option value = "sum159 cell line">sum159 cell line</option>
<option value = "sum159pt breast cancer cells">sum159pt breast cancer cells</option>
<option value = "supernatant (extracted from rpf)">supernatant (extracted from rpf)</option>
<option value = "supernatants of hec-1-a cancer cells">supernatants of hec-1-a cancer cells</option>
<option value = "supraneuralbody">supraneuralbody</option>
<option value = "suspended marine particulate matter">suspended marine particulate matter</option>
<option value = "sweat">sweat</option>
<option value = "synthetic">synthetic</option>
<option value = "t-cells">t-cells</option>
<option value = "t cells">t cells</option>
<option value = "t. kodakarensis cells">t. kodakarensis cells</option>
<option value = "t_mu cells">t_mu cells</option>
<option value = "t24 cells">t24 cells</option>
<option value = "t3m4 pancreatic ductal adenocarcinoma cells">t3m4 pancreatic ductal adenocarcinoma cells</option>
<option value = "t47d breast cancer cells">t47d breast cancer cells</option>
<option value = "tails">tails</option>
<option value = "tear">tear</option>
<option value = "tectum">tectum</option>
<option value = "testis">testis</option>
<option value = "thorax">thorax</option>
<option value = "thymmus">thymmus</option>
<option value = "thyroid">thyroid</option>
<option value = "tissue">tissue</option>
<option value = "tissue (pji)">tissue (pji)</option>
<option value = "tissue homogenate">tissue homogenate</option>
<option value = "tongue tissue">tongue tissue</option>
<option value = "total bone marrow flush (cells)">total bone marrow flush (cells)</option>
<option value = "total rna">total rna</option>
<option value = "toxoplasma gondii">toxoplasma gondii</option>
<option value = "trabecular meshwork">trabecular meshwork</option>
<option value = "tumor">tumor</option>
<option value = "tumor-adjacent normal colon">tumor-adjacent normal colon</option>
<option value = "tumor cells">tumor cells</option>
<option value = "tumor interstitial fluid">tumor interstitial fluid</option>
<option value = "u-87mg brain cancer cells">u-87mg brain cancer cells</option>
<option value = "u251 brain cancer cells">u251 brain cancer cells</option>
<option value = "u2os">u2os</option>
<option value = "u2os cells">u2os cells</option>
<option value = "u2os osteosarcoma cell line">u2os osteosarcoma cell line</option>
<option value = "ulcer biopsies">ulcer biopsies</option>
<option value = "umbilical cord plasma">umbilical cord plasma</option>
<option value = "unspecifed">unspecifed</option>
<option value = "unspecified">unspecified</option>
<option value = "urine">urine</option>
<option value = "uterine fluid">uterine fluid</option>
<option value = "uterine flushing">uterine flushing</option>
<option value = "uterus">uterus</option>
<option value = "vaginal epithelium">vaginal epithelium</option>
<option value = "vascular smooth muscle cells">vascular smooth muscle cells</option>
<option value = "vastus lateralis">vastus lateralis</option>
<option value = "vein plasma">vein plasma</option>
<option value = "ventricle">ventricle</option>
<option value = "ventricles">ventricles</option>
<option value = "ventricles and atria">ventricles and atria</option>
<option value = "visceral adipose tissue">visceral adipose tissue</option>
<option value = "visceral white adipose tissue">visceral white adipose tissue</option>
<option value = "vitreous">vitreous</option>
<option value = "wastewater">wastewater</option>
<option value = "water">water</option>
<option value = "white adipose tissue">white adipose tissue</option>
<option value = "whole adipose tissue">whole adipose tissue</option>
<option value = "whole animals">whole animals</option>
<option value = "whole blood">whole blood</option>
<option value = "whole bodies">whole bodies</option>
<option value = "whole bone">whole bone</option>
<option value = "whole cell lipidomics">whole cell lipidomics</option>
<option value = "whole insect">whole insect</option>
<option value = "whole invertebrate animal">whole invertebrate animal</option>
<option value = "whole larvae">whole larvae</option>
<option value = "whole plant">whole plant</option>
<option value = "whole tissue">whole tissue</option>
<option value = "whole worm extract">whole worm extract</option>
<option value = "whole worm lysate">whole worm lysate</option>
<option value = "whole_body">whole_body</option>
<option value = "wine">wine</option>
<option value = "worms">worms</option>
<option value = "yeast">yeast</option>
<option value = "yeast cells">yeast cells</option>
<option value = "young leaf">young leaf</option>
<option value = "zebrafish">zebrafish</option>
<option value = "zebrafish medium">zebrafish medium</option>
